### ISSUE TITLE
Hi sir, cargo build --release is not working 

### ISSUE THREAD

**Issue by Someone1611** [Ogeon/pyrite#1]

**Comment by Ogeon** [comment]
Hi! That's strange. It has worked fine for me on both Linux and Windows, on two different machines. I'm afraid I can't help you unless you provide the console output from `cargo build` and preferably also the Rust version (`rustc -V` in the project folder).

Also, please keep in mind that this project is only meant as a way for me to learn more about rendering techniques (I should update the readme to be more clear about that). It's not supposed to be more useful than that, although it would be nice to be able to produce a few pretty pictures. It's incomplete, bidirectional tracing is likely incorrect, and photon mapping is straight up broken. But it should at the very least compile! :slightly_smiling_face:

**Comment by Ogeon** [comment]
Any luck with this? Is this issue still needed?

**Comment by Ogeon** [comment]
I'm closing this for now. Feel free to reopen if you happen to come back to it.
